### ISSUE TITLE
Blake2b-512

### ISSUE THREAD

**Issue by dave4you** [saucecontrol/Blake2Fast#2]
Hi,

This is a question regarding the Blake2b implementation.
Is the Blake2Fast.Blake2b implementation also capable of Blake2b-512 message digest?

Kind regards,

Dave

**Comment by saucecontrol** [comment]
Hi Dave.  Yes, 512 bits is the default digest size for BLAKE2b.  The digest size is specified in bytes in the RFC, and it can be anything from 1 to 64 bytes, or 8 to 512 bits (in increments of 8, of course).
